<a href="https://colab.research.google.com/github/ArpanaMahajan30/sales-shipping-performance-analysis/blob/main/Sales_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/train.csv")

In [ ]:
data.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62

In [ ]:
data.shape

(9800, 18)

In [ ]:
data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
data.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [ ]:
# total sales
data['Sales'].sum()

np.float64(2261536.7827000003)

In [ ]:
# sales by category
data.groupby('Category')['Sales'].sum()

Category
Furniture          728658.5757
Office Supplies    705422.3340
Technology         827455.8730
Name: Sales, dtype: float64

In [ ]:
# top 5 products by sales
data.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head()

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
Name: Sales, dtype: float64

In [ ]:
# check missing values
data.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [ ]:
# fill missing postal codes with 0
data['Postal Code'] = data['Postal Code'].fillna(0)

In [ ]:
data.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [ ]:
data['Order Date'] = pd.to_datetime(data['Order Date'], dayfirst=True)

In [ ]:
data['Order Date'].head()

0   2017-11-08
1   2017-11-08
2   2017-06-12
3   2016-10-11
4   2016-10-11
Name: Order Date, dtype: datetime64[ns]

In [ ]:
# convert Order Date to datetime
data['Order Date'] = pd.to_datetime(data['Order Date'])
data['Order Month'] = data['Order Date'].dt.month
data['Order Year'] = data['Order Date'].dt.year

In [ ]:
data['Order Date'].head()

0   2017-11-08
1   2017-11-08
2   2017-06-12
3   2016-10-11
4   2016-10-11
Name: Order Date, dtype: datetime64[ns]

In [ ]:
data[['Order Date', 'Order Month', 'Order Year']].head()

  Order Date  Order Month  Order Year
0 2017-11-08           11        2017
1 2017-11-08           11        2017
2 2017-06-12            6        2017
3 2016-10-11           10        2016
4 2016-10-11           10        2016

In [ ]:
data['Ship Date'] = pd.to_datetime(data['Ship Date'], dayfirst=True)

In [ ]:
data['Ship Date'].head()

0   2017-11-11
1   2017-11-11
2   2017-06-16
3   2016-10-18
4   2016-10-18
Name: Ship Date, dtype: datetime64[ns]

In [ ]:
# convert Ship Date to datetime
data['Ship Date'] = pd.to_datetime(data['Ship Date'])
data['Ship Month'] = data['Ship Date'].dt.month
data['Ship Year'] = data['Ship Date'].dt.year

In [ ]:
data['Ship Date'].head()

0   2017-11-11
1   2017-11-11
2   2017-06-16
3   2016-10-18
4   2016-10-18
Name: Ship Date, dtype: datetime64[ns]

In [ ]:
data[['Ship Date', 'Ship Month', 'Ship Year']].head()

   Ship Date  Ship Month  Ship Year
0 2017-11-11          11       2017
1 2017-11-11          11       2017
2 2017-06-16           6       2017
3 2016-10-18          10       2016
4 2016-10-18          10       2016

In [ ]:
data.to_csv('cleaned_superstore.csv', index=False)

In [ ]:
data[['Order Date', 'Ship Date']].head()

  Order Date  Ship Date
0 2017-11-08 2017-11-11
1 2017-11-08 2017-11-11
2 2017-06-12 2017-06-16
3 2016-10-11 2016-10-18
4 2016-10-11 2016-10-18

In [ ]:
data['Shipping Days'] = (data['Ship Date'] - data['Order Date']).dt.days

In [ ]:
monthly_sales = (
    data.groupby(['Order Year', 'Order Month'])['Sales']
    .sum()
    .reset_index()
    .sort_values(['Order Year', 'Order Month'])
)

monthly_sales.head()

   Order Year  Order Month      Sales
0        2015            1  14205.707
1        2015            2   4519.892
2        2015            3  55205.797
3        2015            4  27906.855
4        2015            5  23644.303

In [ ]:
monthly_sales.sort_values('Sales', ascending=False).head(1)

    Order Year  Order Month       Sales
46        2018           11  117938.155

In [ ]:
monthly_sales.sort_values('Sales').head(1)

   Order Year  Order Month     Sales
1        2015            2  4519.892

In [ ]:
category_sales = data.groupby('Category')['Sales'].sum().reset_index()
category_sales

          Category        Sales
0        Furniture  728658.5757
1  Office Supplies  705422.3340
2       Technology  827455.8730

In [ ]:
data['Shipping Days'] = (data['Ship Date'] - data['Order Date']).dt.days

In [ ]:
data['Shipping Days'].describe()

count    9800.000000
mean        3.961122
std         1.749614
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Shipping Days, dtype: float64

In [ ]:
data.groupby('Category')['Shipping Days'].mean()

Category
Furniture          3.926853
Office Supplies    3.984600
Technology         3.923883
Name: Shipping Days, dtype: float64

📊 Sales & Shipping Performance Analysis

Objective:
Analyze sales performance across product categories and evaluate shipping efficiency using order and ship dates.

🔹 Category-wise Sales Analysis

Grouped data by product category and calculated total sales.

Technology category generated the highest revenue, followed by Furniture and Office Supplies.

Sales distribution indicates that Technology products are the primary revenue drivers.

Insight:
Focusing marketing and inventory strategies on the Technology category can maximize revenue.

🔹 Shipping Duration Analysis

Calculated shipping days as the difference between ship date and order date.

Average shipping time is approximately 4 days.

75% of orders are delivered within 5 days, indicating efficient logistics operations.

Maximum shipping duration observed was 7 days, with no extreme delays.

Insight:
Shipping performance is consistent and reliable, contributing to better customer satisfaction.

✅ Conclusion

Technology category contributes the highest sales.

Shipping operations are stable with predictable delivery timelines.

The analysis provides actionable insights for improving sales strategy and operational efficiency.